In [1484]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB

In [1485]:
df = pd.read_csv('./../patient2025 - patient2025.csv')
df.head()

,HN,FBS,BMI,Diabetes,Chorestorol,age,hypertension,"vegetarian (1= yes, 0=no)",Marriage Status,Exercise (min/week),Living Area,stroke
0,11223,228.69,34.0,yes,201-220,71.0,1,1,Yes,0.0,Bangkok,1
1,8887,202.21,NaN,No,180-200,52.0,1,0,Yes,90.0,Country,1
2,5666,105.92,30.5,yes,180-200,78.0,1,1,Yes,0.0,Country,1
3,460182,171.23,35.0,No,221-260,54.0,1,0,Yes,0.0,Bangkok,1
4,166665,174.12,28.0,No,180-200,79.0,1,0,Yes,90.0,Country,1

fill BMI na ด้วย median

In [1486]:
df["BMI"] = df["BMI"].fillna(df["BMI"].median())
df

,HN,FBS,BMI,Diabetes,Chorestorol,age,hypertension,"vegetarian (1= yes, 0=no)",Marriage Status,Exercise (min/week),Living Area,stroke
0,11223,228.69,34.0,yes,201-220,71.00,1,1,Yes,0.0,Bangkok,1
1,8887,202.21,28.5,No,180-200,52.00,1,0,Yes,90.0,Country,1
2,5666,105.92,30.5,yes,180-200,78.00,1,1,Yes,0.0,Country,1
3,460182,171.23,35.0,No,221-260,54.00,1,0,Yes,0.0,Bangkok,1
4,166665,174.12,28.0,No,180-200,79.00,1,0,Yes,90.0,Country,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,60211,90.51,18.9,yes,Unknown,1.40,0,0,No,120.0,Bangkok,0
996,53279,118.87,16.3,yes,Unknown,0.24,0,0,No,120.0,Country,0
997,61715,56.42,31.8,yes,180-200,55.00,0,0,Yes,0.0,Country,0
998,37830,73.67,21.0,No,Unknown,29.00,0,0,No,0.0,Bangkok,0
999,2454,89.11,20.1,yes,Unknown,4.00,0,0,No,120.0,Country,0

Fill excrcise na ด้วย 0

In [1487]:
df["Exercise (min/week)"] = df["Exercise (min/week)"].fillna(0)
df

,HN,FBS,BMI,Diabetes,Chorestorol,age,hypertension,"vegetarian (1= yes, 0=no)",Marriage Status,Exercise (min/week),Living Area,stroke
0,11223,228.69,34.0,yes,201-220,71.00,1,1,Yes,0.0,Bangkok,1
1,8887,202.21,28.5,No,180-200,52.00,1,0,Yes,90.0,Country,1
2,5666,105.92,30.5,yes,180-200,78.00,1,1,Yes,0.0,Country,1
3,460182,171.23,35.0,No,221-260,54.00,1,0,Yes,0.0,Bangkok,1
4,166665,174.12,28.0,No,180-200,79.00,1,0,Yes,90.0,Country,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,60211,90.51,18.9,yes,Unknown,1.40,0,0,No,120.0,Bangkok,0
996,53279,118.87,16.3,yes,Unknown,0.24,0,0,No,120.0,Country,0
997,61715,56.42,31.8,yes,180-200,55.00,0,0,Yes,0.0,Country,0
998,37830,73.67,21.0,No,Unknown,29.00,0,0,No,0.0,Bangkok,0
999,2454,89.11,20.1,yes,Unknown,4.00,0,0,No,120.0,Country,0

replace Diabetes yes no ด้วย 0 กับ 1

In [1488]:
df["Diabetes"] = df["Diabetes"].replace({
    "yes": 1,
    "No": 0,})
df

C:\Users\Nattanont CSKU\AppData\Local\Temp\ipykernel_6344\2699766147.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Diabetes"] = df["Diabetes"].replace({

,HN,FBS,BMI,Diabetes,Chorestorol,age,hypertension,"vegetarian (1= yes, 0=no)",Marriage Status,Exercise (min/week),Living Area,stroke
0,11223,228.69,34.0,1,201-220,71.00,1,1,Yes,0.0,Bangkok,1
1,8887,202.21,28.5,0,180-200,52.00,1,0,Yes,90.0,Country,1
2,5666,105.92,30.5,1,180-200,78.00,1,1,Yes,0.0,Country,1
3,460182,171.23,35.0,0,221-260,54.00,1,0,Yes,0.0,Bangkok,1
4,166665,174.12,28.0,0,180-200,79.00,1,0,Yes,90.0,Country,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,60211,90.51,18.9,1,Unknown,1.40,0,0,No,120.0,Bangkok,0
996,53279,118.87,16.3,1,Unknown,0.24,0,0,No,120.0,Country,0
997,61715,56.42,31.8,1,180-200,55.00,0,0,Yes,0.0,Country,0
998,37830,73.67,21.0,0,Unknown,29.00,0,0,No,0.0,Bangkok,0
999,2454,89.11,20.1,1,Unknown,4.00,0,0,No,120.0,Country,0

แยกข้อมูลซ้ำดูจาก HN (ไม่มีซ้ำ)

In [1489]:
df = df.drop_duplicates(subset="HN")
df

,HN,FBS,BMI,Diabetes,Chorestorol,age,hypertension,"vegetarian (1= yes, 0=no)",Marriage Status,Exercise (min/week),Living Area,stroke
0,11223,228.69,34.0,1,201-220,71.00,1,1,Yes,0.0,Bangkok,1
1,8887,202.21,28.5,0,180-200,52.00,1,0,Yes,90.0,Country,1
2,5666,105.92,30.5,1,180-200,78.00,1,1,Yes,0.0,Country,1
3,460182,171.23,35.0,0,221-260,54.00,1,0,Yes,0.0,Bangkok,1
4,166665,174.12,28.0,0,180-200,79.00,1,0,Yes,90.0,Country,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,60211,90.51,18.9,1,Unknown,1.40,0,0,No,120.0,Bangkok,0
996,53279,118.87,16.3,1,Unknown,0.24,0,0,No,120.0,Country,0
997,61715,56.42,31.8,1,180-200,55.00,0,0,Yes,0.0,Country,0
998,37830,73.67,21.0,0,Unknown,29.00,0,0,No,0.0,Bangkok,0
999,2454,89.11,20.1,1,Unknown,4.00,0,0,No,120.0,Country,0

drop column ที่ไม่ใช้

In [1490]:
df = df.drop(columns = ['HN', 'Marriage Status', 'Living Area'])
df

,FBS,BMI,Diabetes,Chorestorol,age,hypertension,"vegetarian (1= yes, 0=no)",Exercise (min/week),stroke
0,228.69,34.0,1,201-220,71.00,1,1,0.0,1
1,202.21,28.5,0,180-200,52.00,1,0,90.0,1
2,105.92,30.5,1,180-200,78.00,1,1,0.0,1
3,171.23,35.0,0,221-260,54.00,1,0,0.0,1
4,174.12,28.0,0,180-200,79.00,1,0,90.0,1
...,...,...,...,...,...,...,...,...,...
995,90.51,18.9,1,Unknown,1.40,0,0,120.0,0
996,118.87,16.3,1,Unknown,0.24,0,0,120.0,0
997,56.42,31.8,1,180-200,55.00,0,0,0.0,0
998,73.67,21.0,0,Unknown,29.00,0,0,0.0,0
999,89.11,20.1,1,Unknown,4.00,0,0,120.0,0

replace Chorestorol unknown ด้วย nan

In [1491]:
df["Chorestorol"] = (
    df["Chorestorol"]
    .replace("Unknown", np.nan)
    )
df

,FBS,BMI,Diabetes,Chorestorol,age,hypertension,"vegetarian (1= yes, 0=no)",Exercise (min/week),stroke
0,228.69,34.0,1,201-220,71.00,1,1,0.0,1
1,202.21,28.5,0,180-200,52.00,1,0,90.0,1
2,105.92,30.5,1,180-200,78.00,1,1,0.0,1
3,171.23,35.0,0,221-260,54.00,1,0,0.0,1
4,174.12,28.0,0,180-200,79.00,1,0,90.0,1
...,...,...,...,...,...,...,...,...,...
995,90.51,18.9,1,NaN,1.40,0,0,120.0,0
996,118.87,16.3,1,NaN,0.24,0,0,120.0,0
997,56.42,31.8,1,180-200,55.00,0,0,0.0,0
998,73.67,21.0,0,NaN,29.00,0,0,0.0,0
999,89.11,20.1,1,NaN,4.00,0,0,120.0,0

ทำค่าช่วง Chorestorol ให้เป็น mean

In [1492]:
df[["chol_low", "chol_high"]] = (
    df["Chorestorol"]
    .str.split("-", expand=True)
)

df[["chol_low", "chol_high"]] = df[["chol_low", "chol_high"]].astype(float)

df["Chorestorol"] = df[["chol_low", "chol_high"]].mean(axis=1)
df.drop(columns=["chol_low", "chol_high"], inplace=True)
df

,FBS,BMI,Diabetes,Chorestorol,age,hypertension,"vegetarian (1= yes, 0=no)",Exercise (min/week),stroke
0,228.69,34.0,1,210.5,71.00,1,1,0.0,1
1,202.21,28.5,0,190.0,52.00,1,0,90.0,1
2,105.92,30.5,1,190.0,78.00,1,1,0.0,1
3,171.23,35.0,0,240.5,54.00,1,0,0.0,1
4,174.12,28.0,0,190.0,79.00,1,0,90.0,1
...,...,...,...,...,...,...,...,...,...
995,90.51,18.9,1,NaN,1.40,0,0,120.0,0
996,118.87,16.3,1,NaN,0.24,0,0,120.0,0
997,56.42,31.8,1,190.0,55.00,0,0,0.0,0
998,73.67,21.0,0,NaN,29.00,0,0,0.0,0
999,89.11,20.1,1,NaN,4.00,0,0,120.0,0

fill na ของ Chorestorol ด้วย median (แปลกๆ) ฝากเช็คที

In [1493]:
df["Chorestorol"] = df["Chorestorol"].fillna(df["Chorestorol"].median())
df

# debug = df["Chorestorol"]
# ex_list = []

# for e in debug:
#     if e not in ex_list:
#         ex_list.append(e)

# for ex in ex_list:
#     print(ex)

,FBS,BMI,Diabetes,Chorestorol,age,hypertension,"vegetarian (1= yes, 0=no)",Exercise (min/week),stroke
0,228.69,34.0,1,210.5,71.00,1,1,0.0,1
1,202.21,28.5,0,190.0,52.00,1,0,90.0,1
2,105.92,30.5,1,190.0,78.00,1,1,0.0,1
3,171.23,35.0,0,240.5,54.00,1,0,0.0,1
4,174.12,28.0,0,190.0,79.00,1,0,90.0,1
...,...,...,...,...,...,...,...,...,...
995,90.51,18.9,1,190.0,1.40,0,0,120.0,0
996,118.87,16.3,1,190.0,0.24,0,0,120.0,0
997,56.42,31.8,1,190.0,55.00,0,0,0.0,0
998,73.67,21.0,0,190.0,29.00,0,0,0.0,0
999,89.11,20.1,1,190.0,4.00,0,0,120.0,0

Gaussian Naive Bayes test

In [1494]:
features = ['FBS', 'BMI', 'age', 'Chorestorol', 'Diabetes', 'hypertension', 'vegetarian (1= yes, 0=no)']
X = df[features] # features
y = df.stroke # class

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 6)

model = GaussianNB()

model.fit(X_train, y_train)

predict_test = model.predict(X_test)

print(f"Accuracy: {metrics.accuracy_score(y_test, predict_test)}")
print(metrics.classification_report(y_test, predict_test))

Accuracy: 0.7633333333333333
              precision    recall  f1-score   support

           0       0.83      0.86      0.84       222
           1       0.55      0.50      0.52        78

    accuracy                           0.76       300
   macro avg       0.69      0.68      0.68       300
weighted avg       0.76      0.76      0.76       300

In [1495]:
features = ['Diabetes', 'hypertension', 'vegetarian (1= yes, 0=no)']
X = df[features] # features
y = df.stroke # class

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 6)

model = BernoulliNB()

model.fit(X_train, y_train)

predict_test = model.predict(X_test)

print(f"Accuracy: {metrics.accuracy_score(y_test, predict_test)}")
print(metrics.classification_report(y_test, predict_test))

Accuracy: 0.7566666666666667
              precision    recall  f1-score   support

           0       0.76      0.97      0.86       222
           1       0.65      0.14      0.23        78

    accuracy                           0.76       300
   macro avg       0.71      0.56      0.54       300
weighted avg       0.73      0.76      0.69       300

ลองเลือก feature มาบางส่วนเพื่อใช้ในการ train โดยจะเลือกเฉพาะ feature ที่เป็น 0 หรือ 1 ใช้ MultinomialNB เป็น model ในการ train (Current Best)

In [1496]:
features = ['Diabetes', 'hypertension', 'vegetarian (1= yes, 0=no)']
X = df[features] # features
y = df.stroke # class

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 6)

model = MultinomialNB()
model.fit(X_train, y_train)

predict_test = model.predict(X_test)

print(f"Accuracy: {metrics.accuracy_score(y_test, predict_test)}")
print(metrics.classification_report(y_test, predict_test))

Accuracy: 0.7466666666666667
              precision    recall  f1-score   support

           0       0.74      1.00      0.85       222
           1       1.00      0.03      0.05        78

    accuracy                           0.75       300
   macro avg       0.87      0.51      0.45       300
weighted avg       0.81      0.75      0.64       300